# 1. Data Analysis

Librerias relevantes para el análisis

In [258]:
library(rio)
library(ggplot2)
library(caTools)
library(DescTools)
library(dplyr)
library(Hmisc)
library(psych)

In [259]:
url="https://raw.githubusercontent.com/d2cml-ai/CausalAI-Course/main/data/wage2015_subsample_inference.csv"
wage<-read.csv(url)

In [260]:
names(wage)

 [1] "rownames" "wage"     "lwage"    "sex"      "shs"      "hsg"
 [7] "scl"      "clg"      "ad"       "mw"       "so"       "we"
[13] "ne"       "exp1"     "exp2"     "exp3"     "exp4"     "occ"
[19] "occ2"     "ind"      "ind2"

2. Reporte de NAs

In [261]:
colSums(is.na(wage))

rownames     wage    lwage      sex      shs      hsg      scl      clg
       0        0        0        0        0        0        0        0
      ad       mw       so       we       ne     exp1     exp2     exp3
       0        0        0        0        0        0        0        0
    exp4      occ     occ2      ind     ind2
       0        0        0        0        0

No existen datos perdidos en la base de datos

### 3.  Reporte de estadísticas descriptivas

In [290]:
describe(wage)

              vars n    mean         sd           median       trimmed
rownames       1   5150 1.563635e+04 9.700744e+03 15260.000000 1.546166e+04
wage           2   5150 2.341041e+01 2.100302e+01    19.230769 2.053559e+01
lwage          3   5150 2.970787e+00 5.703848e-01     2.956512 2.956854e+00
sex            4   5150 4.444660e-01 4.969547e-01     0.000000 4.305825e-01
shs            5   5150 2.330097e-02 1.508723e-01     0.000000 0.000000e+00
hsg            6   5150 2.438835e-01 4.294650e-01     0.000000 1.798544e-01
scl            7   5150 2.780583e-01 4.480858e-01     0.000000 2.225728e-01
clg            8   5150 3.176699e-01 4.656155e-01     0.000000 2.720874e-01
ad             9   5150 1.370874e-01 3.439730e-01     0.000000 4.635922e-02
mw            10   5150 2.596117e-01 4.384641e-01     0.000000 1.995146e-01
so            11   5150 2.965049e-01 4.567606e-01     0.000000 2.456311e-01
we            12   5150 2.161165e-01 4.116346e-01     0.000000 1.451456e-01
ne            13   5150 2.277670e-01 4.194322e-01     0.000000 1.597087e-01
exp1          14   5150 1.376058e+01 1.060947e+01    10.000000 1.261080e+01
exp2          15   5150 3.018925e+00 4.000904e+00     1.000000 2.195211e+00
exp3          16   5150 8.235867e+00 1.448896e+01     1.000000 4.632417e+00
exp4          17   5150 2.511804e+01 5.353022e+01     1.000000 1.087759e+01
occ           18   5150 5.310737e+03 1.187436e+04  4040.000000 3.818353e+03
occ2          19   5150 1.167087e+01 6.966684e+00    13.000000 1.178277e+01
ind           20   5150 6.629155e+03 5.333444e+03  7370.000000 6.724626e+03
ind2          21   5150 1.331689e+01 5.701019e+00    14.000000 1.345170e+01
wage_ordinal* 22   5150 2.473204e+00 1.114515e+00     2.000000 2.466505e+00
              mad          min        max          range        skew
rownames      12622.115100  10.000000 3.264300e+04 32633.000000  0.14453716
wage             10.264154   3.021978 5.288457e+02   525.823695 10.76152974
lwage             0.539897   1.105912 6.270697e+00     5.164785  0.37952616
sex               0.000000   0.000000 1.000000e+00     1.000000  0.22345378
shs               0.000000   0.000000 1.000000e+00     1.000000  6.31801090
hsg               0.000000   0.000000 1.000000e+00     1.000000  1.19249205
scl               0.000000   0.000000 1.000000e+00     1.000000  0.99042939
clg               0.000000   0.000000 1.000000e+00     1.000000  0.78302667
ad                0.000000   0.000000 1.000000e+00     1.000000  2.10971318
mw                0.000000   0.000000 1.000000e+00     1.000000  1.09628893
so                0.000000   0.000000 1.000000e+00     1.000000  0.89086334
we                0.000000   0.000000 1.000000e+00     1.000000  1.37903061
ne                0.000000   0.000000 1.000000e+00     1.000000  1.29785060
exp1              8.895600   0.000000 4.700000e+01    47.000000  0.82435187
exp2              1.349166   0.000000 2.209000e+01    22.090000  1.64355286
exp3              1.470739   0.000000 1.038230e+02   103.823000  2.32178623
exp4              1.482452   0.000000 4.879681e+02   487.968100  2.99235596
occ            2816.940000  10.000000 1.000000e+05 99990.000000  7.46761591
occ2              7.413000   1.000000 2.200000e+01    21.000000 -0.23234318
ind            1912.554000 370.000000 1.000000e+05 99630.000000 13.41065110
ind2              7.413000   2.000000 2.200000e+01    20.000000 -0.19190762
wage_ordinal*     1.482600   1.000000 4.000000e+00     3.000000  0.07486349
              kurtosis     se
rownames       -1.21638579 1.351766e+02
wage          210.91873662 2.926699e-01
lwage           1.14948916 7.948118e-03
sex            -1.95044702 6.924894e-03
shs            37.92462584 2.102354e-03
hsg            -0.57807485 5.984448e-03
scl            -1.01924743 6.243923e-03
clg            -1.38713847 6.488194e-03
ad              2.45136580 4.793146e-03
mw             -0.79830548 6.109848e-03
so             -1.20659669 6.364804e-03
we             -0.09829356 5.735989e-03
ne             -0.31564500 5.844645e-03
exp1           -0.37320088 1.478393e-01
exp2            1.94297633 5.575124e-02
exp3            5.35155309 2.018988e-01
exp4           10.17782024 7.459255e-01
occ            56.67967275 1.654651e+02
occ2           -1.32512585 9.707838e-02
ind           234.27639832 7.431973e+01
ind2           -1.21131213 7.944176e-02
wage_ordinal*  -1.34741518 1.553039e-02

**Interpretación** : se puede extraer información relevante si nos enfocamos en la variable del salario del individuo. Se puede observar que el salario promedio de la muestra es de 23.41 dólares.No obstante, la desviación estándar es muy alta(21), lo cual quiere decir que existe una alta dispersión del salario con respecto al promedio. Por ejemplo, existe un individuo cuyo salario es de 528.85 dólares y otro cuyo salario es de 3.02 dólares. En aras de obtener información más estable sobre el salario se recurre a la mediana, la cual nos dice que el 50% de la muestra posee un salario entre los 3.02 y 19.23 dólares. Por último, la muestra presenta una asimetría positiva, lo cual implica que existe un mayor número de trabajadores con un salario menor al promedio.

4. Obtener el número de mujeres con un grado académico alto que poseen un salario del 25% más rico de la muestra

4.1 Identificación de cuantiles

In [263]:
summary(wage$wage)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  3.022  13.461  19.231  23.410  27.778 528.846

4.2 Creamos nueva variable

In [264]:
wage$wage_ordinal=cut(wage$wage, breaks = c(0,13.461,19.231,27.778,528.846),
                      include.lowest = T, ordered_result = T,
                      labels=c("Muy bajo", "Bajo", "Alto","Muy alto"))
table(wage$wage_ordinal)

Muy bajo     Bajo     Alto Muy alto
    1269     1462     1132     1287

4.3 Creamos dos subsets que solo contengan a uno de los sexos

In [265]:
wage_only_women=wage%>%filter(sex == 1)
wage_only_men= wage%>%filter(sex == 0)
wage_only_women$case<- c(1)
wage_only_men$case<- c(1)

4.4 Agrupamos

In [266]:
wage_only_women%>%group_by(clg,wage_ordinal)%>%summarise(Casos=sum(case))

`summarise()` has grouped output by 'clg'. You can override using the `.groups`
argument.

  clg wage_ordinal Casos
1 0   Muy bajo     484
2 0   Bajo         434
3 0   Alto         281
4 0   Muy alto     295
5 1   Muy bajo     107
6 1   Bajo         227
7 1   Alto         224
8 1   Muy alto     237


Existen 237 mujeres con un college dregee que poseen un salario del 25% más rico de la muestra.

In [267]:
wage_only_women%>%group_by(ad,wage_ordinal)%>%summarise(Casos=sum(case))

`summarise()` has grouped output by 'ad'. You can override using the `.groups`
argument.

  ad wage_ordinal Casos
1 0  Muy bajo     558
2 0  Bajo         581
3 0  Alto         392
4 0  Muy alto     357
5 1  Muy bajo      33
6 1  Bajo          80
7 1  Alto         113
8 1  Muy alto     175

Existen 175 mujeres con un advanced degree que poseen un salario del 25% más rico de la muestra. En ambos dataframes, las mujeres que no poseen alguno de estos grados académicos tienden a ser más propensas a tener un salario del 25% menos rico de la muestra, en comparación a las mujeres que sí poseen un mayor nivel académico. Ello nos lleva a inferir que probablemente el nivel educativo puede influir en la obtención de mejores salarios.

5. Obtener el número de hombres con un grado académico medio-bajo que poseen un salario perteneciente al 25% más rico de la muestra

In [268]:
wage_only_men%>%group_by(hsg, wage_ordinal)%>%summarise(Casos=sum(case))

`summarise()` has grouped output by 'hsg'. You can override using the `.groups`
argument.

  hsg wage_ordinal Casos
1 0   Muy bajo     369
2 0   Bajo         525
3 0   Alto         477
4 0   Muy alto     648
5 1   Muy bajo     309
6 1   Bajo         276
7 1   Alto         150
8 1   Muy alto     107

Existen 107 trabajadores hombres con secundaria completa que poseen un salario perteneciente al 25% más rico de la muestra.

In [269]:
wage_only_men%>%group_by(shs, wage_ordinal)%>%summarise(Casos=sum(case))

`summarise()` has grouped output by 'shs'. You can override using the `.groups`
argument.

  shs wage_ordinal Casos
1 0   Muy bajo     634
2 0   Bajo         775
3 0   Alto         614
4 0   Muy alto     747
5 1   Muy bajo      44
6 1   Bajo          26
7 1   Alto          13
8 1   Muy alto       8

Existen solo 8 trabajadores hombres con secundaria incompleta que tienen un salario perteneciente al 25% más rico de la muestra. Para ambos casos, los hombres que no poseen alguno de estos grados educativos son más propensos a poseer un salario pertenenciente al 25% más pobre. Si comparamos estos resultados con el anterior grupo, podemos observar que hay más mujeres con un salario altísimo en comparación con los hombres, pero ello puede deberse al mayor nivel educativo que poseen.

6. Creación de dos bases de datos

In [270]:
Y=wage%>%select(3)

In [271]:
X=wage%>%select(!(2:3))

8. Hacer tres matrices para nuestros predictores

In [272]:
names(X)

 [1] "rownames"     "sex"          "shs"          "hsg"          "scl"
 [6] "clg"          "ad"           "mw"           "so"           "we"
[11] "ne"           "exp1"         "exp2"         "exp3"         "exp4"
[16] "occ"          "occ2"         "ind"          "ind2"         "wage_ordinal"

Primero convertimos en dummy las variables "occ2" y "ind2"

In [273]:
X<- fastDummies::dummy_cols(X, select_columns = "occ2",remove_first_dummy = TRUE)
X<- fastDummies::dummy_cols(X, select_columns = "ind2",remove_first_dummy = TRUE)

In [274]:
names(X)

 [1] "rownames"     "sex"          "shs"          "hsg"          "scl"
 [6] "clg"          "ad"           "mw"           "so"           "we"
[11] "ne"           "exp1"         "exp2"         "exp3"         "exp4"
[16] "occ"          "occ2"         "ind"          "ind2"         "wage_ordinal"
[21] "occ2_2"       "occ2_3"       "occ2_4"       "occ2_5"       "occ2_6"
[26] "occ2_7"       "occ2_8"       "occ2_9"       "occ2_10"      "occ2_11"
[31] "occ2_12"      "occ2_13"      "occ2_14"      "occ2_15"      "occ2_16"
[36] "occ2_17"      "occ2_18"      "occ2_19"      "occ2_20"      "occ2_21"
[41] "occ2_22"      "ind2_3"       "ind2_4"       "ind2_5"       "ind2_6"
[46] "ind2_7"       "ind2_8"       "ind2_9"       "ind2_10"      "ind2_11"
[51] "ind2_12"      "ind2_13"      "ind2_14"      "ind2_15"      "ind2_16"
[56] "ind2_17"      "ind2_18"      "ind2_19"      "ind2_20"      "ind2_21"
[61] "ind2_22"

8.1

In [275]:
X_1=X%>%select(!c(mw,wage_ordinal,ind,rownames,exp2,exp3,exp4))

8.2

In [276]:
X_2=X%>%select(!c(mw,wage_ordinal,ind,rownames))

In [277]:
experience<- X%>%select(exp1,exp2,exp3,exp4)

In [278]:
names(X)

 [1] "rownames"     "sex"          "shs"          "hsg"          "scl"
 [6] "clg"          "ad"           "mw"           "so"           "we"
[11] "ne"           "exp1"         "exp2"         "exp3"         "exp4"
[16] "occ"          "occ2"         "ind"          "ind2"         "wage_ordinal"
[21] "occ2_2"       "occ2_3"       "occ2_4"       "occ2_5"       "occ2_6"
[26] "occ2_7"       "occ2_8"       "occ2_9"       "occ2_10"      "occ2_11"
[31] "occ2_12"      "occ2_13"      "occ2_14"      "occ2_15"      "occ2_16"
[36] "occ2_17"      "occ2_18"      "occ2_19"      "occ2_20"      "occ2_21"
[41] "occ2_22"      "ind2_3"       "ind2_4"       "ind2_5"       "ind2_6"
[46] "ind2_7"       "ind2_8"       "ind2_9"       "ind2_10"      "ind2_11"
[51] "ind2_12"      "ind2_13"      "ind2_14"      "ind2_15"      "ind2_16"
[56] "ind2_17"      "ind2_18"      "ind2_19"      "ind2_20"      "ind2_21"
[61] "ind2_22"

In [279]:
experience_2<- X%>%select(!c(mw,wage_ordinal,ind,rownames,sex,exp1,exp2,exp3,exp4))

In [280]:
for (exp in experience) {
    new_df=exp*experience_2
    print(new_df)
}

      shs hsg  scl clg ad so we   ne       occ  occ2  ind2 occ2_2 occ2_3 occ2_4
1     0.0   0  0.0   7  0  0  0  7.0   25200.0  77.0 126.0    0.0    0.0    0.0
2     0.0   0  0.0  31  0  0  0 31.0   94550.0 310.0 279.0    0.0    0.0    0.0
3     0.0  18  0.0   0  0  0  0 18.0  112680.0 342.0  72.0    0.0    0.0    0.0
4     0.0   0  0.0   0 25  0  0 25.0   10500.0  25.0 300.0    0.0    0.0    0.0
5     0.0   0  0.0  22  0  0  0 22.0   44330.0 132.0 484.0    0.0    0.0    0.0
6     0.0   0  0.0   1  0  0  0  1.0    1650.0   5.0  14.0    0.0    0.0    0.0
7     0.0  42  0.0   0  0  0  0 42.0  215040.0 714.0 588.0    0.0    0.0    0.0
8     0.0  37  0.0   0  0  0  0 37.0  193880.0 629.0 333.0    0.0    0.0    0.0
9     0.0  31  0.0   0  0  0  0 31.0  125240.0 403.0 589.0    0.0    0.0    0.0
10    0.0   0  0.0   4  0  0  0  4.0   13020.0  40.0  72.0    0.0    0.0    0.0
11    0.0   7  0.0   0  0  0  0  7.0   28140.0  91.0 126.0    0.0    0.0    0.0
12    0.0  30  0.0   0  0  0  0 30.0  126600.0 420.0 540.0    0.0    0.0    0.0
13    0.0   0  5.5   0  0  0  0  5.5   19800.0  60.5  99.0    0.0    0.0    0.0
14    0.0   0 20.5   0  0  0  0 20.5   74722.5 225.5 369.0    0.0    0.0    0.0
15    0.0   0  0.0  25  0  0  0 25.0    2750.0  25.0 425.0    0.0    0.0    0.0
16    0.0  16  0.0   0  0  0  0 16.0  101680.0 304.0  64.0    0.0    0.0    0.0
17    0.0  27  0.0   0  0  0  0 27.0  170640.0 513.0 108.0    0.0    0.0    0.0
18    0.0   0  3.5   0  0  0  0  3.5   25935.0  70.0  10.5    0.0    0.0    0.0
19    0.0   6  0.0   0  0  0  0  6.0   42000.0 120.0  54.0    0.0    0.0    0.0
20    0.0   8  0.0   0  0  0  0  8.0   32000.0 104.0 160.0    0.0    0.0    0.0
21    0.0   0  6.5   0  0  0  0  6.5   27950.0  97.5 123.5    0.0    0.0    0.0
22    0.0   0  8.5   0  0  0  0  8.5   30600.0  93.5 153.0    0.0    0.0    0.0
23    0.0   0  0.0   0 11  0  0 11.0   25410.0  88.0 187.0    0.0    0.0    0.0
24    0.0   0  0.0  11  0  0  0 11.0   68200.0 209.0  44.0    0.0    0.0    0.0
25    0.0   0 24.5   0  0  0  0 24.5     490.0  24.5 220.5    0.0    0.0    0.0
26    0.0   8  0.0   0  0  0  0  8.0   38400.0 128.0 112.0    0.0    0.0    0.0
27    0.0   5  0.0   0  0  0  0  5.0    2150.0   5.0  70.0    0.0    0.0    0.0
28    0.0   0  4.5   0  0  0  0  4.5   28485.0  85.5  18.0    0.0    0.0    0.0
29    0.0   0  0.0   8  0  0  0  8.0   43200.0 136.0  72.0    0.0    0.0    0.0
30    0.0   0  0.0  26  0  0  0 26.0  161980.0 494.0 286.0    0.0    0.0    0.0
31    0.0   0  0.0   0  0  0  0  0.0       0.0   0.0   0.0    0.0    0.0    0.0
32    0.0   0 15.5   0  0  0  0 15.5   90830.0 263.5 139.5    0.0    0.0    0.0
33    0.0   0  9.0   0  0  0  0  9.0   31500.0  90.0 162.0    0.0    0.0    0.0
34    0.0   0  0.0   0 14  0  0 14.0   32620.0 112.0 238.0    0.0    0.0    0.0
35    0.0  14  0.0   0  0  0  0 14.0    6020.0  14.0  84.0    0.0    0.0    0.0
36    0.0   5  0.0   0  0  0  0  5.0   44825.0 105.0  30.0    0.0    0.0    0.0
37    0.0   0  0.0  31  0  0  0 31.0   81530.0 279.0 279.0    0.0    0.0    0.0
38    0.0   0  0.0   0 28  0  0 28.0  129080.0 420.0 504.0    0.0    0.0    0.0
39    0.0  11  0.0   0  0  0  0 11.0  100430.0 242.0 110.0    0.0    0.0    0.0
40    0.0   0  0.0  11  0  0  0 11.0   51700.0 176.0  99.0    0.0    0.0    0.0
41    0.0   0 17.5   0  0  0  0 17.5   94500.0 297.5 192.5    0.0    0.0    0.0
42    0.0  12  0.0   0  0  0  0 12.0  109560.0 264.0 120.0    0.0    0.0    0.0
43    0.0  15  0.0   0  0  0  0 15.0   54000.0 165.0 270.0    0.0    0.0    0.0
44    0.0  27  0.0   0  0  0  0 27.0   97200.0 297.0 486.0    0.0    0.0    0.0
45    0.0   0  6.5   0  0  0  0  6.5   26715.0  84.5 130.0    0.0    0.0    0.0
46    0.0  12  0.0   0  0  0  0 12.0  115440.0 264.0 252.0    0.0    0.0    0.0
47    0.0  41  0.0   0  0  0  0 41.0  394420.0 902.0 369.0    0.0    0.0    0.0
48    0.0   0 17.5   0  0  0  0 17.5   82600.0 280.0 157.5    0.0    0.0    0.0
49    0.0   0  0.0   7  0  0  0  7.0   41020.0 119.0  84.0    0.0    0.0    0.0
50    0.0   0  0.0   0 23  0  0 23.0     460.0  23.0 460.0    0.0    0.0    0.0
51    0.0   0 34.5   0  0  0  0 34.5  310500.0 759.0 310.5    0.0    0.0    0.0
52    0.0   0  0.0  10  0  0  0 10.0    7250.0  20.0 190.0   10.0    0.0    0.0
53    0.0  36  0.0   0  0  0  0 36.0  322740.0 756.0 180.0    0.0    0.0    0.0
54    0.0   0  0.0   0 35  0  0 35.0   80850.0 280.0 595.0    0.0    0.0    0.0
55    0.0   0  0.0   0 27  0  0 27.0   22950.0  54.0 324.0   27.0    0.0    0.0
56    0.0  41  0.0   0  0  0  0 41.0  147600.0 451.0 738.0    0.0    0.0    0.0
57    0.0  15  0.0   0  0  0  0 15.0   60150.0 195.0 300.0    0.0    0.0    0.0
58    0.0   0  0.0  23  0  0  0 23.0   76360.0 230.0 414.0    0.0    0.0    0.0
59    0.0  26  0.0   0  0  0  0 26.0  104520.0 338.0 468.0    0.0    0.0    0.0
60    0.0   0  4.5   0  0  0  0  4.5   18990.0  63.0  85.5    0.0    0.0    0.0
61    0.0   0  0.0  21  0  0  0 21.0  117600.0 357.0 126.0    0.0    0.0    0.0
62    0.0  29  0.0   0  0  0  0 29.0  165300.0 493.0 522.0    0.0    0.0    0.0
63    0.0   0  0.0   2  0  0  0  2.0   11880.0  34.0  36.0    0.0    0.0    0.0
64    0.0   0  0.0   5  0  0  0  5.0   38150.0 100.0  35.0    0.0    0.0    0.0
65    0.0   0  0.0  27  0  0  0 27.0    3240.0  27.0 324.0    0.0    0.0    0.0
66    0.0   0 33.0   0  0  0  0 33.0  254100.0 693.0 165.0    0.0    0.0    0.0
67    0.0   0  0.0   7  0  0  0  7.0   25480.0  77.0 119.0    0.0    0.0    0.0
68    0.0  25  0.0   0  0  0  0 25.0  100500.0 325.0 500.0    0.0    0.0    0.0
69    0.0   7  0.0   0  0  0  0  7.0   47740.0 133.0  28.0    0.0    0.0    0.0
70    0.0   0  0.0   0 19  0  0 19.0   38190.0 114.0 418.0    0.0    0.0    0.0
71    0.0   0  0.0   3  0  0  0  3.0   14280.0  48.0  27.0    0.0    0.0    0.0
72    0.0  36  0.0   0  0  0  0 36.0  117180.0 360.0 648.0    0.0    0.0    0.0
73    0.0  19  0.0   0  0  0  0 19.0   78090.0 247.0 380.0    0.0    0.0    0.0
74    0.0  28  0.0   0  0  0  0 28.0  118160.0 392.0 476.0    0.0    0.0    0.0
75    0.0   0 34.0   0  0  0  0 34.0  119000.0 340.0 612.0    0.0    0.0    0.0
76    0.0  33  0.0   0  0  0  0 33.0  271260.0 693.0 198.0    0.0    0.0    0.0
77    0.0   0  0.0  10  0  0  0 10.0   23100.0  80.0 170.0    0.0    0.0    0.0
78    0.0  12  0.0   0  0  0  0 12.0     600.0  12.0 168.0    0.0    0.0    0.0
79    0.0   0  5.5   0  0  0  0  5.5   20350.0  66.0 121.0    0.0    0.0    0.0
80    0.0   7  0.0   0  0  0  0  7.0   39900.0 119.0  42.0    0.0    0.0    0.0
81    0.0  10  0.0   0  0  0  0 10.0   62300.0 190.0  40.0    0.0    0.0    0.0
82    0.0   9  0.0   0  0  0  0  9.0   56340.0 171.0  36.0    0.0    0.0    0.0
83    0.0  25  0.0   0  0  0  0 25.0  106250.0 350.0 400.0    0.0    0.0    0.0
84    0.0   0 26.5   0  0  0  0 26.5  128525.0 424.0 185.5    0.0    0.0    0.0
85    0.0   0  0.0  20  0  0  0 20.0  114000.0 340.0 320.0    0.0    0.0    0.0
86   37.0   0  0.0   0  0  0  0 37.0  251600.0 703.0  74.0    0.0    0.0    0.0
87    0.0  19  0.0   0  0  0  0 19.0  146300.0 399.0 114.0    0.0    0.0    0.0
88   26.0   0  0.0   0  0  0  0 26.0 2600000.0 546.0 130.0    0.0    0.0    0.0
89    0.0   0  3.0   0  0  0  0  3.0   21600.0  60.0  63.0    0.0    0.0    0.0
90    0.0   0  0.0   2  0  0  0  2.0    1700.0   4.0  24.0    2.0    0.0    0.0
91    0.0   0  0.0   4  0  0  0  4.0    2940.0   8.0  36.0    4.0    0.0    0.0
92    0.0   0  0.0   4  0  0  0  4.0    2840.0   8.0  56.0    4.0    0.0    0.0
93    0.0   5  0.0   0  0  0  0  5.0   18000.0  55.0  90.0    0.0    0.0    0.0
94    0.0   0  4.0   0  0  0  0  4.0   28800.0  80.0  84.0    0.0    0.0    0.0
95    0.0   0  4.5   0  0  0  0  4.5   28035.0  85.5  18.0    0.0    0.0    0.0
96    0.0   0  4.5   0  0  0  0  4.5  450000.0  90.0  45.0    0.0    0.0    0.0
97    0.0   0  0.0   1  0  0  0  1.0     850.0   2.0  14.0    1.0    0.0    0.0
98    0.0   0  0.0   2  0  0  0  2.0   14400.0  40.0  18.0    0.0    0.0    0.0
99    0.0   0  0.0   5  0  0  0  5.0   11550.0  40.0  85.0    0.0    0.0    0.0
100   0.0   0  0.0  38  0  0  0 38.0  194560.0 646.0 532.0    0.0    0.0    0.0
101   0.0  21  0.0   0  0  0  0 21.0  161700.0 441.0 126.0    0.0    0.0    0.0
102   0.0   0  0.0  25  0  0  0 25.0  107500.0 375.0 475.0    0.0    0.0    0.0
103   0.0   0  7.5   0  0  0  0  7.5   42075.0 127.5  45.0    0.0    0.0    0.0
104   0.0  12  0.0   0  0  0  0 12.0    5160.0  12.0  72.0    0.0    0.0    0.0
105   0.0   0 16.5   0  0  0  0 16.5   69630.0 231.0 297.0    0.0    0.0    0.0
106   0.0   9  0.0   0  0  0  0  9.0   32400.0  99.0 162.0    0.0    0.0    0.0
107   0.0   0 33.0   0  0  0  0 33.0  107415.0 330.0 561.0    0.0    0.0    0.0
108  29.0   0  0.0   0  0  0  0 29.0  122380.0 406.0 377.0    0.0    0.0    0.0
109   0.0   0  0.0   1  0  0  0  1.0    4610.0  15.0  18.0    0.0    0.0    0.0
110   0.0   0  0.0   1  0  0  0  1.0    4220.0  14.0  16.0    0.0    0.0    0.0
111   0.0   0  0.0  15  0  0  0 15.0   60300.0 195.0 300.0    0.0    0.0    0.0
112   0.0   0  0.0   0 30  0  0 30.0   69600.0 240.0 510.0    0.0    0.0    0.0
113   0.0   0  3.5   0  0  0  0  3.5   11970.0  35.0  31.5    0.0    0.0    0.0
114   0.0   0  0.0  18  0  0  0 18.0   14940.0  36.0 216.0   18.0    0.0    0.0
115   0.0   0  0.0   5  0  0  0  5.0    3250.0  10.0  90.0    5.0    0.0    0.0
116   0.0   0 23.5   0  0  0  0 23.5  123140.0 399.5 305.5    0.0    0.0    0.0
117   0.0   0 29.5   0  0  0  0 29.5  140420.0 472.0 265.5    0.0    0.0    0.0
118   0.0   5  0.0   0  0  0  0  5.0   44825.0 105.0  30.0    0.0    0.0    0.0
119   0.0   0  6.5   0  0  0  0  6.5   37050.0 110.5 143.0    0.0    0.0    0.0
120   0.0   0  0.0   1  0  0  0  1.0    5000.0  17.0   9.0    0.0    0.0    0.0
121   0.0   0  0.0  19  0  0  0 19.0  182780.0 418.0  95.0    0.0    0.0    0.0
122   0.0   0  0.0   0  7  0  0  7.0   16240.0  56.0 119.0    0.0    0.0    0.0
123   0.0   0  0.0   2  0  0  0  2.0    1600.0   4.0  28.0    2.0    0.0    0.0
124   0.0   0  0.0   0 29  0  0 29.0  136300.0 464.0 261.0    0.0    0.0    0.0
125   0.0   0 35.5   0  0  0  0 35.5  324115.0 781.0 355.0    0.0    0.0    0.0
126   0.0   0 32.5   0  0  0  0 32.5  170300.0 552.5 162.5    0.0    0.0    0.0
127   0.0   0 29.5   0  0  0  0 29.5  168150.0 501.5 649.0    0.0    0.0    0.0
128   0.0   0  0.0   0  2  0  0  2.0    1600.0   4.0  28.0    2.0    0.0    0.0
129   0.0   0  0.0  13  0  0  0 13.0   72800.0 221.0 143.0    0.0    0.0    0.0
130   0.0   0  8.0   0  0  0  0  8.0     880.0   8.0 176.0    0.0    0.0    0.0
131   0.0   0  6.5   0  0  0  0  6.5   51675.0 136.5  39.0    0.0    0.0    0.0
132   0.0  31  0.0   0  0  0  0 31.0     620.0  31.0 279.0    0.0    0.0    0.0
133   0.0  16  0.0   0  0  0  0 16.0  115200.0 320.0 336.0    0.0    0.0    0.0
134   0.0   0  0.0  23  0  0  0 23.0    9660.0  23.0 483.0    0.0    0.0    0.0
135  28.0   0  0.0   0  0  0  0 28.0  112560.0 364.0 560.0    0.0    0.0    0.0
136   0.0  14  0.0   0  0  0  0 14.0   59220.0 196.0 280.0    0.0    0.0    0.0
137   0.0  40  0.0   0  0  0  0 40.0  188000.0 640.0 360.0    0.0    0.0    0.0
138   0.0   0  0.0   1  0  0  0  1.0    2000.0   6.0  17.0    0.0    0.0    0.0
139   0.0   0  0.0  15  0  0  0 15.0   48825.0 150.0 270.0    0.0    0.0    0.0
140   0.0   0  0.0  10  0  0  0 10.0   58000.0 170.0 120.0    0.0    0.0    0.0
141   0.0   8  0.0   0  0  0  0  8.0   32320.0 104.0 160.0    0.0    0.0    0.0
142   0.0   0  0.0   0 10  0  0 10.0   23100.0  80.0 170.0    0.0    0.0    0.0
143   0.0   0 13.5   0  0  0  0 13.5   53055.0 162.0 216.0    0.0    0.0    0.0
144   0.0   0  0.0  12  0  0  0 12.0   12720.0  36.0 144.0    0.0   12.0    0.0
145   0.0   0  0.0   9  0  0  0  9.0    4860.0  18.0 108.0    9.0    0.0    0.0
146   0.0   0 16.0   0  0  0  0 16.0   93760.0 272.0 352.0    0.0    0.0    0.0
147   0.0   0  0.0   0  0  0  0  0.0       0.0   0.0   0.0    0.0    0.0    0.0
148   0.0   0  0.0   3  0  0  0  3.0    2205.0   6.0  24.0    3.0    0.0    0.0
149   0.0   0 15.5   0  0  0  0 15.5  126170.0 325.5  93.0    0.0    0.0    0.0
150   0.0   0  0.0   1  0  0  0  1.0      20.0   1.0  20.0    0.0    0.0    0.0
151   0.0  20  0.0   0  0  0  0 20.0  112200.0 340.0 100.0    0.0    0.0    0.0
152   0.0   0  5.0   0  0  0  0  5.0   18000.0  55.0  90.0    0.0    0.0    0.0
153   0.0   0  8.0   0  0  0  0  8.0    2480.0   8.0 160.0    0.0    0.0    0.0
154   0.0   0 10.5   0  0  0  0 10.5   65520.0 199.5  42.0    0.0    0.0    0.0
155   0.0   0  0.0   5  0  0  0  5.0    3150.0  10.0  90.0    5.0    0.0    0.0
156   0.0   0  0.0   6  0  0  0  6.0   12000.0  36.0 102.0    0.0    0.0    0.0
157   0.0  12  0.0   0  0  0  0 12.0   57120.0 192.0 108.0    0.0    0.0    0.0
158   0.0  12  0.0   0  0  0  0 12.0   99060.0 252.0  60.0    0.0    0.0    0.0
159   0.0  29  0.0   0  0  0  0 29.0  264770.0 638.0 290.0    0.0    0.0    0.0
160   0.0   0  0.0  13  0  0  0 13.0   10400.0  26.0 286.0   13.0    0.0    0.0
161   0.0   0  0.0   0  1  0  0  1.0    1650.0   5.0  22.0    0.0    0.0    0.0
162   0.0   0 17.5   0  0  0  0 17.5   18375.0  52.5 245.0    0.0   17.5    0.0
163   0.0   0  0.0  21  0  0  0 21.0    9030.0  21.0 294.0    0.0    0.0    0.0
164   0.0   0  0.0   6  0  0  0  6.0   52440.0 126.0  36.0    0.0    0.0    0.0
165   0.0   0 31.5   0  0  0  0 31.5   82845.0 283.5 189.0    0.0    0.0    0.0
166   0.0   0  4.0   0  0  0  0  4.0    4200.0  12.0  68.0    0.0    4.0    0.0
167   0.0   0  6.5   0  0  0  0  6.5    3510.0  13.0  78.0    6.5    0.0    0.0
168   0.0   0  0.0   4  0  0  0  4.0   22800.0  68.0  56.0    0.0    0.0    0.0
169   0.0  36  0.0   0  0  0  0 36.0  295920.0 756.0 216.0    0.0    0.0    0.0
170   0.0   0  0.0  24  0  0  0 24.0  116400.0 384.0 144.0    0.0    0.0    0.0
171   0.0   0  3.5   0  0  0  0  3.5   18935.0  59.5  56.0    0.0    0.0    0.0
172   0.0   0  0.0   2  0  0  0  2.0   15440.0  42.0  12.0    0.0    0.0    0.0
173   0.0   0  0.0   0  5  0  0  5.0   15750.0  50.0  90.0    0.0    0.0    0.0
174   0.0  33  0.0   0  0  0  0 33.0  301290.0 726.0 330.0    0.0    0.0    0.0
175   0.0   0  0.0  14  0  0  0 14.0   32340.0 112.0 238.0    0.0    0.0    0.0
176   0.0   0  0.0  18  0  0  0 18.0   11340.0  36.0  72.0   18.0    0.0    0.0
177   0.0   0  0.0  18  0  0  0 18.0   10170.0  36.0 216.0   18.0    0.0    0.0
178   0.0   5  0.0   0  0  0  0  5.0   20550.0  65.0 100.0    0.0    0.0    0.0
179   0.0   7  0.0   0  0  0  0  7.0   29540.0  98.0 119.0    0.0    0.0    0.0
180   0.0   0  0.0  29  0  0  0 29.0   67860.0 232.0 406.0    0.0    0.0    0.0
181   0.0   0  5.5   0  0  0  0  5.5    1705.0   5.5 110.0    0.0    0.0    0.0
182   0.0   0  0.0   5  0  0  0  5.0    3150.0  10.0  45.0    5.0    0.0    0.0
183   0.0   0  3.5   0  0  0  0  3.5    8050.0  28.0  63.0    0.0    0.0    0.0
184   0.0   0  9.0   0  0  0  0  9.0   42300.0 144.0  81.0    0.0    0.0    0.0
185   0.0   0  7.0   0  0  0  0  7.0   65940.0 154.0  70.0    0.0    0.0    0.0
186   0.0   0  0.0   3  0  0  0  3.0   12660.0  42.0  24.0    0.0    0.0    0.0
187   0.0   0 10.5   0  0  0  0 10.5   58905.0 178.5  63.0    0.0    0.0    0.0
188   0.0   0  0.0  33  0  0  0 33.0   36465.0  99.0 462.0    0.0   33.0    0.0
189   0.0   0 19.5   0  0  0  0 19.5   91650.0 312.0 175.5    0.0    0.0    0.0
190   0.0   0 29.0   0  0  0  0 29.0  165300.0 493.0 522.0    0.0    0.0    0.0
191   0.0   0  0.0   0  9  0  0  9.0    3780.0   9.0 189.0    0.0    0.0    0.0
192   0.0   0  0.0   3  0  0  0  3.0   15720.0  51.0  36.0    0.0    0.0    0.0
193   0.0   0 13.0   0  0  0  0 13.0   47385.0 143.0 234.0    0.0    0.0    0.0
194   0.0  20  0.0   0  0  0  0 20.0  128000.0 380.0  80.0    0.0    0.0    0.0
195   0.0   0  4.5   0  0  0  0  4.5   25290.0  76.5  40.5    0.0    0.0    0.0
196   0.0   0  0.0   6  0  0  0  6.0   24000.0  78.0 120.0    0.0    0.0    0.0
197   0.0   0  4.0   0  0  0  0  4.0   16000.0  52.0  76.0    0.0    0.0    0.0
198   0.0   0  3.0   0  0  0  0  3.0    9765.0  30.0  54.0    0.0    0.0    0.0
199   0.0   0  0.0   0  0  0  0  0.0       0.0   0.0   0.0    0.0    0.0    0.0
200   0.0   8  0.0   0  0  0  0  8.0   49760.0 152.0  32.0    0.0    0.0    0.0
201   0.0   0  0.0   4  0  0  0  4.0   23440.0  68.0  64.0    0.0    0.0    0.0
202   0.0   0  0.0  29  0  0  0 29.0   12470.0  29.0 174.0    0.0    0.0    0.0
203   0.0   0  4.5   0  0  0  0  4.5   23040.0  76.5  40.5    0.0    0.0    0.0
204   0.0  14  0.0   0  0  0  0 14.0   87080.0 266.0  56.0    0.0    0.0    0.0
205   0.0   0  0.0   0 29  0  0 29.0   93670.0 290.0 493.0    0.0    0.0    0.0
206   0.0   0  0.0   0 31  0  0 31.0  142600.0 465.0 558.0    0.0    0.0    0.0
207   0.0   0 30.0   0  0  0  0 30.0  210000.0 600.0 270.0    0.0    0.0    0.0
208   0.0   9  0.0   0  0  0  0  9.0   37890.0 126.0 144.0    0.0    0.0    0.0
209   0.0   7  0.0   0  0  0  0  7.0   62755.0 147.0  42.0    0.0    0.0    0.0
210   0.0   0  0.0   0 37  0  0 37.0  194620.0 629.0 407.0    0.0    0.0    0.0
211   0.0   0  0.0  32  0  0  0 32.0   73920.0 256.0 544.0    0.0    0.0    0.0
212   0.0  14  0.0   0  0  0  0 14.0  108500.0 294.0  84.0    0.0    0.0    0.0
213   0.0   0 15.5   0  0  0  0 15.5   88350.0 263.5 139.5    0.0    0.0    0.0
214   0.0  14  0.0   0  0  0  0 14.0  121940.0 294.0  70.0    0.0    0.0    0.0
215   0.0   0  0.0   8  0  0  0  8.0   38080.0 128.0  72.0    0.0    0.0    0.0
216   0.0   0  0.0  13  0  0  0 13.0   26130.0  78.0 286.0    0.0    0.0    0.0
217   0.0   0  4.0   0  0  0  0  4.0   22400.0  68.0  72.0    0.0    0.0    0.0
218   0.0   0  0.0   3  0  0  0  3.0   25620.0  63.0  18.0    0.0    0.0    0.0
219   0.0   0  0.0   0 37  0  0 37.0   85470.0 296.0 629.0    0.0    0.0    0.0
220   0.0  29  0.0   0  0  0  0 29.0  264770.0 638.0 464.0    0.0    0.0    0.0
221   0.0   0  0.0  13  0  0  0 13.0   42315.0 130.0 221.0    0.0    0.0    0.0
222   0.0   0  0.0   0 15  0  0 15.0    6450.0  15.0 165.0    0.0    0.0    0.0
223   0.0   8  0.0   0  0  0  0  8.0   51520.0 152.0  32.0    0.0    0.0    0.0
224   0.0  30  0.0   0  0  0  0 30.0  231000.0 630.0 180.0    0.0    0.0    0.0
225   0.0   0 28.0   0  0  0  0 28.0   56000.0 168.0 616.0    0.0    0.0    0.0
226   0.0   0  0.0   0  6  0  0  6.0   12000.0  36.0 102.0    0.0    0.0    0.0
227   0.0   0  0.0  20  0  0  0 20.0   40200.0 120.0 360.0    0.0    0.0    0.0
228   0.0   0  0.0   0 23  0  0 23.0   36800.0 115.0 391.0    0.0    0.0    0.0
229   0.0   0  0.0   2  0  0  0  2.0    4020.0  12.0  36.0    0.0    0.0    0.0
230   0.0   0  0.0   4  0  0  0  4.0    8000.0  24.0  72.0    0.0    0.0    0.0
231   0.0   0 13.0   0  0  0  0 13.0   82615.0 247.0  39.0    0.0    0.0    0.0
232   0.0   0 17.0   0  0  0  0 17.0   74800.0 255.0 323.0    0.0    0.0    0.0
233   0.0   0  0.0   0  2  0  0  2.0    4200.0  14.0  28.0    0.0    0.0    0.0
234   0.0   0  0.0  16  0  0  0 16.0   46400.0 144.0 272.0    0.0    0.0    0.0
235   0.0  10  0.0   0  0  0  0 10.0   57000.0 170.0  90.0    0.0    0.0    0.0
236   0.0   0  7.5   0  0  0  0  7.5   19725.0  67.5 105.0    0.0    0.0    0.0
237   0.0   7  0.0   0  0  0  0  7.0   57540.0 147.0  42.0    0.0    0.0    0.0
238   0.0   0  0.0   2  0  0  0  2.0    5620.0  18.0  22.0    0.0    0.0    0.0
239   0.0   0 30.5   0  0  0  0 30.5  143960.0 488.0 671.0    0.0    0.0    0.0
240   0.0   0 15.0   0  0  0  0 15.0   51300.0 150.0 210.0    0.0    0.0    0.0
241   0.0   0  0.0   3  0  0  0  3.0    6930.0  24.0  51.0    0.0    0.0    0.0
242   0.0   0  0.0   6  0  0  0  6.0   28200.0  96.0  54.0    0.0    0.0    0.0
243   0.0   0  4.5   0  0  0  0  4.5   23895.0  76.5  81.0    0.0    0.0    0.0
244   0.0   0  5.0   0  0  0  0  5.0    7750.0  20.0  25.0    0.0    0.0    5.0
245   0.0  27  0.0   0  0  0  0 27.0  127170.0 432.0 189.0    0.0    0.0    0.0
246   0.0  16  0.0   0  0  0  0 16.0  146080.0 352.0 160.0    0.0    0.0    0.0
247   0.0  12  0.0   0  0  0  0 12.0    3720.0  12.0 240.0    0.0    0.0    0.0
248   0.0   0  0.0   0 30  0  0 30.0   97650.0 300.0 540.0    0.0    0.0    0.0
249   0.0   0  0.0   3  0  0  0  3.0    5895.0  15.0  51.0    0.0    0.0    0.0

In [281]:
X_2.1<-data.frame(X_2,new_df)

8.3

In [282]:
X_3<-data.frame(X_2['sex'],(X_2%>%select(!(sex)))^2)

# 3. Linear Regressions

9.

In [283]:
data_1<- data.frame(Y,X_1)
data_2<- data.frame(Y,X_2.1)
data_3<- data.frame(Y,X_3)

In [284]:
sample_1 <- sample.split(data_1$lwage, SplitRatio = 0.80)
train_1 <- subset(data_1, sample_1 == TRUE)
test_1 <- subset(data_1, sample_1 == FALSE)

sample_2 <- sample.split(data_2$lwage, SplitRatio = 0.80)
train_2 <- subset(data_2, sample_2 == TRUE)
test_2 <- subset(data_2, sample_2 == FALSE)

sample_3 <- sample.split(data_3$lwage, SplitRatio = 0.80)
train_3 <- subset(data_3, sample_3 == TRUE)
test_3 <- subset(data_3, sample_3 == FALSE)

10. Estimando los modelos

In [285]:
modelo_1<-lm(lwage~., data=train_1)
modelo_2<- lm(lwage~., data=train_2)
modelo_3<- lm(lwage~., data=train_3)

Estimamos la variable dependiente predicha por el modelo en grupo de prueba

In [286]:
y_1_test=test_1$lwage
y_2_test=test_2$lwage
y_3_test=test_3$lwage


y_1_test_pred = predict(modelo_1, test_1%>%select(!(lwage)))
y_2_test_pred = predict(modelo_2, test_2%>%select(!(lwage)))
y_3_test_pred = predict(modelo_3, test_3%>%select(!(lwage)))

Warning message in predict.lm(modelo_3, test_3 %>% select(!(lwage))):
"prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases"

In [287]:
mse_1_test=mean((y_1_test - y_1_test_pred)^2)
mse_2_test=mean((y_2_test - y_2_test_pred)^2)
mse_3_test=mean((y_3_test - y_3_test_pred)^2)

print(paste0("MSE out of sample of basic model is ", mse_1_test))
print(paste0("MSE out of sample of flexible model is ", mse_2_test))
print(paste0("MSE out of sample of more flexible model is ", mse_3_test))

R_sq_1_test= 1 - mse_1_test / mean((y_1_test - mean(y_1_test))^2)
R_sq_2_test = 1 - mse_2_test / mean((y_2_test - mean(y_2_test))^2)
R_sq_3_test = 1 - mse_3_test / mean((y_3_test - mean(y_3_test))^2)

print(paste0("R-squared out of sample of basic model is ", R_sq_1_test))
print(paste0("R-squared out of sample of flexible model is ", R_sq_2_test))
print(paste0("R-squared out of sample of more flexible model is ", R_sq_3_test))

adj_mse_1_test = 1030 / (1030-55) * mse_1_test
adjR_sq_1_test = 1 - adj_mse_1_test / mean((y_1_test-mean(y_1_test))^2)

adj_mse_2_test = 1030 / (1030-110) * mse_2_test
adjR_sq_2_test = 1 - adj_mse_2_test / mean((y_2_test-mean(y_2_test))^2)

adj_mse_3_test = 1030 / (1030-58) * mse_3_test
adjR_sq_3_test = 1 - adj_mse_3_test / mean((y_3_test-mean(y_3_test))^2)

print(paste0("Adjusted R-squared out of sample of basic model  is ", adjR_sq_1_test))
print(paste0("Adjusted R-squared out of sample of flexible model  is ", adjR_sq_2_test))
print(paste0("Adjusted R-squared out of sample of more flexible model is ", adjR_sq_3_test))

[1] "MSE out of sample of basic model is 0.202993200097623"
[1] "MSE out of sample of flexible model is 0.188199615413922"
[1] "MSE out of sample of more flexible model is 0.193945961775633"
[1] "R-squared out of sample of basic model is 0.255451193904896"
[1] "R-squared out of sample of flexible model is 0.309711857852355"
[1] "R-squared out of sample of more flexible model is 0.288635115769549"
[1] "Adjusted R-squared out of sample of basic model  is 0.213451004843121"
[1] "Adjusted R-squared out of sample of flexible model  is 0.227177406073832"
[1] "Adjusted R-squared out of sample of more flexible model is 0.246187416916292"

In [288]:
y_1_train=train_1$lwage
y_2_train=train_2$lwage
y_3_train=train_3$lwage

y_1_train_pred = predict(modelo_1, train_1%>%select(!(lwage)))
y_2_train_pred = predict(modelo_2, train_2%>%select(!(lwage)))
y_3_train_pred = predict(modelo_3, train_3%>%select(!(lwage)))

Warning message in predict.lm(modelo_3, train_3 %>% select(!(lwage))):
"prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases"

In [289]:
mse_1_train=mean((y_1_train - y_1_train_pred)^2)
mse_2_train=mean((y_2_train - y_2_train_pred)^2)
mse_3_train=mean((y_3_train - y_3_train_pred)^2)

print(paste0("MSE in the sample of basic model is ", mse_1_train))
print(paste0("MSE in the sample of flexible model is ", mse_2_train))
print(paste0("MSE in the sample of more flexible model is ", mse_3_train))

R_sq_1_train= 1 - mse_1_train / mean((y_1_train - mean(y_1_train))^2)
R_sq_2_train = 1 - mse_2_train / mean((y_2_train - mean(y_2_train))^2)
R_sq_3_train = 1 - mse_3_train / mean((y_3_train - mean(y_3_train))^2)

print(paste0("R-squared in the sample of basic model is ", R_sq_1_train))
print(paste0("R-squared in the sample of flexible model is ", R_sq_2_train))
print(paste0("R-squared in the sample of more flexible model is ", R_sq_3_train))

adj_mse_1_train = 1030 / (1030-55) * mse_1_train
adjR_sq_1_train = 1 - adj_mse_1_test / mean((y_1_train-mean(y_1_train))^2)

adj_mse_2_train = 1030 / (1030-110) * mse_2_train
adjR_sq_2_train = 1 - adj_mse_2_train / mean((y_2_train-mean(y_2_train))^2)

adj_mse_3_train = 1030 / (1030-58) * mse_3_train
adjR_sq_3_train = 1 - adj_mse_3_train / mean((y_3_train-mean(y_3_train))^2)

print(paste0("Adjusted R-squared in the sample of basic model  is ", adjR_sq_1_train))
print(paste0("Adjusted R-squared in the sample of flexible model  is ", adjR_sq_2_train))
print(paste0("Adjusted R-squared in the sample of more flexible model is ", adjR_sq_3_train))

[1] "MSE in the sample of basic model is 0.229287076577505"
[1] "MSE in the sample of flexible model is 0.22615859438363"
[1] "MSE in the sample of more flexible model is 0.229795374938077"
[1] "R-squared in the sample of basic model is 0.316769316641703"
[1] "R-squared in the sample of flexible model is 0.326091582244722"
[1] "R-squared in the sample of more flexible model is 0.315254686853461"
[1] "Adjusted R-squared in the sample of basic model  is 0.360998490663008"
[1] "Adjusted R-squared in the sample of flexible model  is 0.245515575773982"
[1] "Adjusted R-squared in the sample of more flexible model is 0.274395398620438"

Interpretación: 
- En términos generales, los tres modelos presentan métricas de predicción más altas en el conjunto de entrenamiento, en comparación cuando se evalúan en el conjunto de prueba. 
- En el conjunto de entrenamiento, se puede observar que el modelo flexible tiene un mayor r cuadrado(0.327) en comparación con el modelo básico y el modelo más flexible. No obstante, cuando utilizamos el r cuadrado ajustado, el cual incluye una penalidad por la inclusión de variables irrelevantes, podemos observar que el modelo básico es el que posee la mayor capacidad predictiva (0.361). 
- Los resultados de evaluación en el conjunto de entrenamiento no se pueden replicar en el conjunto de prueba, pues allí el modelo que posee una mayor capacidad predictiva es el modelo más flexible (0.246)
- Se puede identificar un  ligero caso de overfitting con el segundo modelo, el que posee  el mayor número de variables (110), debido a que cuando se evalúa su capacidad predictiva en el conjunto de prueba, sus indicadores de evaluación decaen ligeramente (MSE_Train: 0.226, MSE_Test: 0.1881), (R2_Train: 0.326, R2_Test: 0.310), (Rajustado_Train: 0.245, Rajustado_Test: 0.227)